### ISSUE TITLE
View cell ouputs

### ISSUE THREAD

**Issue by shuvrobiswas** [paulgb/runipy#104]
When I run an IPython notebook, I see

12/01/2015 12:34:51 AM INFO: Cell returned
12/01/2015 12:34:51 AM INFO: Running cell
...

as output, but anything printed out or produced by cells do not show up in command line. Is this the default behavior? Is there a way to see what is happening in the output cells of an IPython notebook?

**Comment by jakirkham** [comment]
TL;DR -- This is the current behavior, yes.

Workaround -- A resultant notebook can be written out to a file or stream. Note this will not appear as nice on the stream.

Long Answer -- It would be nice to fix this. The original issue is here ( https://github.com/paulgb/runipy/issues/9 ). This likely requires some more significant changes in the internals, which has not been approached yet. I don't have an estimation at present as to when I might get to this. If you want to give it a shot, you are more than welcome to.

**Comment by jakirkham** [comment]
Closing as duplicate. Please direct further discussion here ( https://github.com/paulgb/runipy/issues/9 ).
