### ISSUE TITLE
runipy as a background process

### ISSUE THREAD

**Issue by tuanvu216** [paulgb/runipy#113]
Hi,

Is there a way I can run ```nohup runipy &``` as a background process?

Thanks,
Tuan

**Comment by jakirkham** [comment]
Sure, there shouldn't be any problem running it as a background process. Are you running into issues doing so?

**Comment by tuanvu216** [comment]
Sorry, I figure it out. I will close this issue.

**Comment by jakirkham** [comment]
Ok, well, if you run into issues again, feel free to let me know.
