### ISSUE TITLE
no stop command

### ISSUE THREAD

**Issue by schmittlema** [paulgb/runipy#118]
Hi,
This is a great program and I am excited to use it, but I couldn't find any documentation on stoping a program from running. Ctl -C did not seem to work. My program is intended to run forever until stopped then it generates a graph of the result, so I was hoping there was a stop command I just missed.

Thanks!

**Comment by jakirkham** [comment]
Thanks for the suggestion. So, the idea of `runipy` is to be run in batch. However, it seems like you are looking for an interactive feature. Is there a reason not to be using a Jupyter notebook to do this?

**Comment by paulgb** [comment]
Ctrl+C will stop the execution of the entire notebook, not just the current cell. For this use case I don't think runipy is the right tool.
