### ISSUE TITLE
request: use runipy as a regression tester

### ISSUE THREAD

**Issue by dsblank** [paulgb/runipy#14]
It would be very useful to be able to run notebooks and compare the output with the previous stored output and return values in the notebook. For example:

runipy --test MyOldNotebook.ipynb
Running tests...
.......F..F...
Two cells failed. 
Cell 34 failed on output: expected: "Ok", actual: "Not ok"
Cell 56 failed on retval value: expected "23", actual: "23.01"   

It seems that this functionality would be easily added to your code, but is a question if you want it in there, or in a separate tool.

Thanks for considering this feature!

**Comment by jakirkham** [comment]
Sounds kind of like [pytest-ipynb](https://pypi.python.org/pypi/pytest-ipynb). Would that work for you?

**Comment by jakirkham** [comment]
@dsblank, sounds kind of like [pytest-ipynb](https://pypi.python.org/pypi/pytest-ipynb). Would that work for you?

**Comment by jakirkham** [comment]
At present, I think `pytest-ipynb` already does this quite nicely and am not interested in trying to duplicate it.

**Comment by dsblank** [comment]
Thanks! Will take a look.
