### ISSUE TITLE
Sphinx Error

### ISSUE THREAD

**Issue by quasiben** [paulgb/runipy#27]
When using runipy with notebook_sphinxext I receive the following error:

```bash
Exception AttributeError: "'NotebookRunner' object has no attribute 'kc'" in 
<bound method NotebookRunner.__del__ of
 <runipy.notebook_runner.NotebookRunner object at 0x105371b10>> 
ignored
```

**Comment by jakirkham** [comment]
If someone has a simple example that would be really nice, I also have not used this extension and have no way to reproduce it at present.

**Comment by jakirkham** [comment]
@ngoldbaum, are using this same tool, as well? If so, are you still having issues with it?

**Comment by ngoldbaum** [comment]
No. In any case, the issue should probably be filed against my RunNotebook repo rather than this one. I'd say this is safe to close.

**Comment by jakirkham** [comment]
Ok, sounds good. Thanks @ngoldbaum.
