### ISSUE TITLE
%load_ext pymatbridge doesn't block

### ISSUE THREAD

**Issue by mfitzp** [paulgb/runipy#34]
I've come across a rather strange error when trying to run notebooks containing %%matlab magic. This worked with the version of pymatbridge here: https://github.com/jaderberg/python-matlab-bridge  

But the latest version here: https://github.com/arokem/python-matlab-bridge/tree/master/pymatbridge using a ZMQ-socket-based server is not so happy. Looking at the output it appears that the processing of subsequent cells continues without waiting for the magic cell to complete (not sure if this is accurate). This ends in a hang which is only recoverable by killing the kernel.

    INFO:root:Running cell:
    %load_ext pymatbridge
    
    INFO:root:Cell returned
    INFO:root:Running cell:
    datamatrix = input_data.values.T

    INFO:root:Cell returned
    INFO:root:Running cell:
    %%matlab -i datamatrix,points -o datamatrixbucketed
    datamatrixbucketed = spcbucket(datamatrix, points);

    Warning: No window system found.  Java option 'MWT' ignored

                                < M A T L A B (R) >
                      Copyright 1984-2010 The MathWorks, Inc.
                    Version 7.12.0.635 (R2011a) 64-bit (maci64)
                                   March 18, 2011

    Warning: Duplicate directory name: /Users/mxf793/matlab. 
 
      To get started, type one of these: helpwin, helpdesk, or demo.
      For product information, visit www.mathworks.com.
 

      Student License -- for use in conjunction with courses offered at a 
      degree-granting institution.  Professional and commercial use prohibited.

Running this same notebook in the web interface is fine. The %%load_ext pymatbridge cell outputs: 

    Starting MATLAB on ZMQ socket ipc:///tmp/pymatbridge
    Send 'exit' command to kill the server
    .MATLAB started and connected!

Any ideas what is going on? Thanks!

**Comment by paulgb** [comment]
I'm doing some housekeeping and closing this as I don't think it's a general problem with runipy. If you're still having issues let me know.
