### ISSUE TITLE
environment variables option for programmatic use

### ISSUE THREAD

**Issue by JohnGriffiths** [paulgb/runipy#40]
Hi. 

Could you please add just a few lines to the README to explain how one would do the equivalent of the unix environment argument passing when reading in and running the notebook in pure python using NotebookRunnerr, etc.

Thanks!

**Comment by jakirkham** [comment]
So, are you just wanting see something like this.

> Set environment variables in Python like so.
>
>     import os
>     os.environ["VAR"] = "VAL"
