### ISSUE TITLE
runipy hangs on --html option

### ISSUE THREAD

**Issue by git42** [paulgb/runipy#41]
Runipy is writing the html file but does not exit.

How to reproduce:
- install CentOS release 6.5 (Final)
- build Python 2.7.8 from source
- pip install
Jinja2==2.7.3
MarkupSafe==0.23
Pygments==1.6
backports.ssl-match-hostname==3.4.0.2
certifi==14.05.14
ipython==2.2.0
psycopg2==2.5.4
pyzmq==14.3.1
runipy==0.1.1
tornado==4.0.2
wsgiref==0.1.2
- start ipython notebook
- create new notebook tom_hangs with one cell containing: print "tom hangs"
- run runipy tom_hangs.ipynb --html

Besides that, I think, you wanted to append the extension 'html' to the html-report in line 101 of main.py (see https://github.com/paulgb/runipy/blob/master/runipy/main.py#L101).

**Comment by paulgb** [comment]
Merged #47, thanks @tfrench
