### ISSUE TITLE
runipy doesn't play well with python-markdown extension (understandably)

### ISSUE THREAD

**Issue by helgridly** [paulgb/runipy#45]
I have the [python-markdown](https://github.com/ipython-contrib/IPython-notebook-extensions/wiki/python-markdown) extension installed, and therefore have Markdown cells whose output is defined by the execution of previous cells.

Currently, runipy only executes code cells and leaves Markdown cells as-is. I understand that extensions are written in Javascript, and pretending to be a browser is *probably* outside the remit of runipy... but hypothetically, what would be required to get this working?

**Comment by paulgb** [comment]
Thanks @helgridly. You're right in that full generalized extension support would require browser emulation and is outside the scope of runipy. I'm glad you found a solution that worked in your case.
