### ISSUE TITLE
runipy doesn't execute ipython profile startup scripts

### ISSUE THREAD

**Issue by airhorns** [paulgb/runipy#46]
We use startup scripts to set up a bunch of connections and configuration necessary for our notebooks to execute to keep the code in the notebooks simple. It would appear as though runipy just starts sending cells to a kernel without executing those startup scripts, which means notebooks break in all sorts of ways.

I am not super familiar with the IPython source code but I would guess this is because runipy doesn't use a subclass of the `InteractiveShellApp` doodad thing and instead just manages its own kernel. See https://github.com/ipython/ipython/blob/2.x/IPython/core/shellapp.py#L357

@paulgb am I missing something? What do you think about switching to using an App subclass to execute or something like that?

**Comment by paulgb** [comment]
I don't use startup scripts, so I'm not sure if it's the same as the profile directory, but does #39 close this issue?

**Comment by hagino3000** [comment]
> but does #39 close this issue?

@paulgb Yes, I using startup scripts with #39 branch version.
