### ISSUE TITLE
Exception if interactive widgets are used

### ISSUE THREAD

**Issue by rlabbe** [paulgb/runipy#60]
I have a notebook that includes IPython.html.widgets interactive widgets. When runipy reaches the cell that calls interact(), it raises

    NotImplementedError: unhandled iopub message: comm_open

**Comment by jolos** [comment]
I can confirm, I encounter the same error.

**Comment by jakirkham** [comment]
Also seeing this error.

**Comment by jakirkham** [comment]
This is a dup of #32.
